// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_push_topic_ from "./routes/api/push/[topic].ts";
import * as $api_subscribe from "./routes/api/subscribe.ts";
import * as $api_vapid from "./routes/api/vapid.ts";
import * as $index from "./routes/index.tsx";
import * as $SubscribeBanner from "./islands/SubscribeBanner.tsx";
import * as $signals_push from "./islands/signals/push.ts";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/push/[topic].ts": $api_push_topic_,
    "./routes/api/subscribe.ts": $api_subscribe,
    "./routes/api/vapid.ts": $api_vapid,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/SubscribeBanner.tsx": $SubscribeBanner,
    "./islands/signals/push.ts": $signals_push,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
